import { Artwork } from '@/types';
export const artworksBatch1: Artwork[] = [
  {
    id: '2',
    artist: '최윤정',
    title: 'face #02-홍범도',
    description: '',
    size: '53x53cm',
    material: 'oil on canvas',
    year: '2023',
    edition: '',
    price: '₩4,500,000',
    image: '2.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/21',
  },
  {
    id: '3',
    artist: '최윤정',
    title: 'pop kids #96',
    description: '',
    size: '53x53cm',
    material: 'oil on canvas',
    year: '2016',
    edition: '',
    price: '₩4,500,000',
    image: '3.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/22',
  },
  {
    id: '4',
    artist: '이수철',
    title: '포르코 당신은 어디있나요?-1',
    description: '',
    size: '70x46.6cm',
    material: 'pigment print on paper',
    year: '2011',
    edition: '에디션 5/5',
    price: '₩1,000,000',
    image: '4.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/23',
  },
  {
    id: '5',
    artist: '이광수',
    title: '回1',
    description: '',
    size: '60x45cm',
    material: '캔버스에 아크릴',
    year: '',
    edition: '',
    price: '₩1,200,000',
    image: '5.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/24',
    sold: true,
  },
  {
    id: '6',
    artist: '이광수',
    title: '回2',
    description: '',
    size: '60x45cm',
    material: '캔버스에 아크릴',
    year: '',
    edition: '',
    price: '₩1,200,000',
    image: '6.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/25',
  },
  {
    id: '7',
    artist: '안소현',
    title: '무제',
    description: `NEW REMINISCENCE [새로운 회상]\n가끔은 내 나라말이 아닌데도 노래의 가사를 느끼는 경우가 있다. 나에겐 順子 Shunza의【寫一首歌 APRIL 5 1969】그랬다. 그녀의 청아한 목소리에 퍼지는 공명과 함께 들려오는 중국의 언어는 무언가를 회상하는 듯이 심연의 사랑을 노래하고 있었다. 이처럼 사진 속에도 언어가 있다. 나는 우연적으로 박제해버린 시공간 속에 언어를 해석하여 들려주는 노래와 같은 작업을 해왔다. 나에게 말을 거는 혹은 내가 말을 건 사진 속에 언어를 해석하고 꺼내었다. 무겁지 않은 시선으로 선율이 들리는 풍경들을 찾아 그들과 마주하였다. 본 전시 중 수영장을 배경으로 한 Hokney 02 라는 작품의 경우 2018년 [CITY OASIS] 개인전 당시 많이 들었던 데이비드 호크니 작품을 직접적으로 오마주 하였다. 이것은 관람객이 끼친 영향력을 통한 새로운 작품으로의 길이 되는 중요한 순간이었다. 새로운 회상들에 대한 언어들로 또 다른 새로운 회상을 만드는 것이다. COVID-19 직전에 촬영한 이번 전시작들은 생생한 추억을 모티브로 더 화려하게 어쩌면 미화된 모습으로 작업하였다. 발 닿을 수 있는 곳에 어떤 제약없이 갈 수 있었던 장소가 이제는 보이지 않는 벽에 막혀 하나의 몽환적인 꿈처럼 느껴진다는 것이 주된 관점이 되어 시각화 하였다. 매 순간은 살아남는 과정이 되고, 우리는 태어남과 죽음을, 극단적 균형을 경험하고 있다. 무한할 것만 같은 일상이 심히 유한 하였음을 깨달았다. 알 수 없는 그리움이 만들어낸 지금의 모습이 어쩌면 이 작업물들을 깨워버린 인간이라는 동물의 방어 기제인지도 모르겠다.`,
    size: '73x106.5cm',
    material: 'pigment print',
    year: '2018',
    edition: '에디션 1/8',
    price: '₩2,400,000',
    image: '7.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/26',
  },
  {
    id: '8',
    artist: '안소현',
    title: 'Authentic City',
    description: `NEW REMINISCENCE [새로운 회상]\n가끔은 내 나라말이 아닌데도 노래의 가사를 느끼는 경우가 있다. 나에겐 順子 Shunza의【寫一首歌 APRIL 5 1969】그랬다. 그녀의 청아한 목소리에 퍼지는 공명과 함께 들려오는 중국의 언어는 무언가를 회상하는 듯이 심연의 사랑을 노래하고 있었다. 이처럼 사진 속에도 언어가 있다. 나는 우연적으로 박제해버린 시공간 속에 언어를 해석하여 들려주는 노래와 같은 작업을 해왔다. 나에게 말을 거는 혹은 내가 말을 건 사진 속에 언어를 해석하고 꺼내었다. 무겁지 않은 시선으로 선율이 들리는 풍경들을 찾아 그들과 마주하였다. 본 전시 중 수영장을 배경으로 한 Hokney 02 라는 작품의 경우 2018년 [CITY OASIS] 개인전 당시 많이 들었던 데이비드 호크니 작품을 직접적으로 오마주 하였다. 이것은 관람객이 끼친 영향력을 통한 새로운 작품으로의 길이 되는 중요한 순간이었다. 새로운 회상들에 대한 언어들로 또 다른 새로운 회상을 만드는 것이다. COVID-19 직전에 촬영한 이번 전시작들은 생생한 추억을 모티브로 더 화려하게 어쩌면 미화된 모습으로 작업하였다. 발 닿을 수 있는 곳에 어떤 제약없이 갈 수 있었던 장소가 이제는 보이지 않는 벽에 막혀 하나의 몽환적인 꿈처럼 느껴진다는 것이 주된 관점이 되어 시각화 하였다. 매 순간은 살아남는 과정이 되고, 우리는 태어남과 죽음을, 극단적 균형을 경험하고 있다. 무한할 것만 같은 일상이 심히 유한 하였음을 깨달았다. 알 수 없는 그리움이 만들어낸 지금의 모습이 어쩌면 이 작업물들을 깨워버린 인간이라는 동물의 방어 기제인지도 모르겠다.`,
    size: '60x80cm',
    material: 'pigment print',
    year: '2023',
    edition: '에디션 1/10',
    price: '₩1,500,000',
    image: '8.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/27',
  },
  {
    id: '9',
    artist: '안소현',
    title: 'Authentic City',
    description: `NEW REMINISCENCE [새로운 회상]\n가끔은 내 나라말이 아닌데도 노래의 가사를 느끼는 경우가 있다. 나에겐 順子 Shunza의【寫一首歌 APRIL 5 1969】그랬다. 그녀의 청아한 목소리에 퍼지는 공명과 함께 들려오는 중국의 언어는 무언가를 회상하는 듯이 심연의 사랑을 노래하고 있었다. 이처럼 사진 속에도 언어가 있다. 나는 우연적으로 박제해버린 시공간 속에 언어를 해석하여 들려주는 노래와 같은 작업을 해왔다. 나에게 말을 거는 혹은 내가 말을 건 사진 속에 언어를 해석하고 꺼내었다. 무겁지 않은 시선으로 선율이 들리는 풍경들을 찾아 그들과 마주하였다. 본 전시 중 수영장을 배경으로 한 Hokney 02 라는 작품의 경우 2018년 [CITY OASIS] 개인전 당시 많이 들었던 데이비드 호크니 작품을 직접적으로 오마주 하였다. 이것은 관람객이 끼친 영향력을 통한 새로운 작품으로의 길이 되는 중요한 순간이었다. 새로운 회상들에 대한 언어들로 또 다른 새로운 회상을 만드는 것이다. COVID-19 직전에 촬영한 이번 전시작들은 생생한 추억을 모티브로 더 화려하게 어쩌면 미화된 모습으로 작업하였다. 발 닿을 수 있는 곳에 어떤 제약없이 갈 수 있었던 장소가 이제는 보이지 않는 벽에 막혀 하나의 몽환적인 꿈처럼 느껴진다는 것이 주된 관점이 되어 시각화 하였다. 매 순간은 살아남는 과정이 되고, 우리는 태어남과 죽음을, 극단적 균형을 경험하고 있다. 무한할 것만 같은 일상이 심히 유한 하였음을 깨달았다. 알 수 없는 그리움이 만들어낸 지금의 모습이 어쩌면 이 작업물들을 깨워버린 인간이라는 동물의 방어 기제인지도 모르겠다.`,
    size: '40x50cm',
    material: 'pigment print',
    year: '2023',
    edition: '에디션 2/10',
    price: '₩600,000',
    image: '9.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/28',
  },
  {
    id: '10',
    artist: '신예리',
    title: '야형화접도(夜螢花蝶圖)',
    description: '',
    size: '24x114cm',
    material: '먹 염색한 한지 위에 분채',
    year: '2023',
    edition: '',
    price: '₩4,000,000',
    image: '10.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/29',
  },
  {
    id: '11',
    artist: '신예리',
    title: '책거리',
    description: '',
    size: '103.5x68.3cm',
    material: '염색한지 위에 분채',
    year: '2020',
    edition: '',
    price: '₩6,000,000',
    image: '11.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/30',
  },
  {
    id: '12',
    artist: '손은영',
    title: 'The Houses at Night,2021, #81',
    description:
      '집은 가족 구성원 간의 사랑과 따뜻함, 안락함 등의 정서적 경험과 친밀감을 느끼는 일상생활에서 가장 중요한 장소이다. 집은 사람들이 많은 시간을 보내고, 추억을 만들어 내는 장소이고, 집에 대한 기억은 자신의 가족, 친구, 지역사회 등과의 연관성을 떠올리게 하며, 이는 자기 삶의 의미와 방향성을 제시하는 역할을 한다. 집은 가족 구성원과 끊을 수 없는 유대감과 공동 운명체라는 정서가 녹아 있고, 추억을 공유하고 미래의 꿈을 꿈꿔 왔던 삶의 중요한 장소이다.\n시대가 변화함에 따라 집의 의미도 점차 변화하지만, 여전히 집에는 개인의 지난 시절의 추억, 경험과 더불어 자신의 모습이 담겨있다. 집이 품고 있는 따뜻함과 보호받음은 집이 지닌 모성(母性)이고, 몸에 각인된 모성으로 인해 어린 시절의 기억이 스며있는 그 집들이 이제는 존재하지 않더라도 여전히 사라지지 않는 최후의 가치로 남아 있게 된다.\n나는 《검은 집》(2020년)을 시작으로, 《밤의 집》(2021년), 2023년 《기억의 집》, 2024년 5월 13일 전시 예정인 《그 집에 산다》까지 집이라는 장소에 주목하여 작업의 중요 소재로 삼아 왔다.\n나에게 집은 가족과의 정서적 유대감이 충만한 장소이면서도 가족의 부재에서 비롯된 상실감이 혼재된 장소이다. 나의 기억 속 집은 온 가족들이 함께하지 못하고 종종 혼자 지내는 장소이기도 했다. 집 연작들은 이러한 과거의 기억에서 비롯한다. 한 지붕 밑에 온 가족이 모여, 웃고 즐기면서 이야기하는 꿈을 자주 꾸곤 했다.\n《밤의 집》과 《기억의 집》이 집을 정물처럼 근접한 거리에서 정적인 시선으로 접근하여 바라봤다면 이번 《그 집에 산다》는 집들이 함께 어울어져 모여 있는 골목을 중심으로 바라보고자 했다. 서울과 지방을 오고 가며 촬영한 다양한 형태의 집들을 마치 도색 하듯이 색을 입히고, 낡거나 헌 물건을 고치듯이 새롭게 표현하고자 했다. 사람의 온기와 친밀도를 느낄 수 있도록 따뜻한 색조를 많이 사용하고자 했다.\n청소년 시절의 어린 마음에는, 집은 어디에나 있지만, 가족 구성원이 희로애락을 함께 나눌 수 있는 진정한 의미의 집은 어디에도 없을 것으로 생각하곤 했다. 그러나 인간은 기억하고 싶은 것만 기억하듯이 자전적 기억 속의 집은 아름답고 근사한 자태로 그리움으로 남아 있다. 현대인에게도 여전히 인간을 위한 진정한 집은 어디에 있는지, 집은 인간에게 어떤 의미가 있는지, 풀리지 않는 수수께끼처럼 남아 있다.\n청소년기에 겪었던 가족에 대한 그리움과 애틋한 기억과 돌아갈 수 없는 시절의 노스탤지어 감성으로 집의 진정한 의미를 찾아 가는 여정을 통해 이 시대를 살아가는데 필요한 진정한 위안과 집이라는 장소에 깃든 삶의 아름다움과 특별함을 표현하고자 한다.',
    size: '60x80cm',
    material: 'Archival pigment print',
    year: '2022',
    edition: '',
    price: '₩2,500,000',
    image: '12.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/31',
  },
  {
    id: '13',
    artist: '손은영',
    title: '언덕위의 집',
    description:
      '집은 가족 구성원 간의 사랑과 따뜻함, 안락함 등의 정서적 경험과 친밀감을 느끼는 일상생활에서 가장 중요한 장소이다. 집은 사람들이 많은 시간을 보내고, 추억을 만들어 내는 장소이고, 집에 대한 기억은 자신의 가족, 친구, 지역사회 등과의 연관성을 떠올리게 하며, 이는 자기 삶의 의미와 방향성을 제시하는 역할을 한다. 집은 가족 구성원과 끊을 수 없는 유대감과 공동 운명체라는 정서가 녹아 있고, 추억을 공유하고 미래의 꿈을 꿈꿔 왔던 삶의 중요한 장소이다.\n시대가 변화함에 따라 집의 의미도 점차 변화하지만, 여전히 집에는 개인의 지난 시절의 추억, 경험과 더불어 자신의 모습이 담겨있다. 집이 품고 있는 따뜻함과 보호받음은 집이 지닌 모성(母性)이고, 몸에 각인된 모성으로 인해 어린 시절의 기억이 스며있는 그 집들이 이제는 존재하지 않더라도 여전히 사라지지 않는 최후의 가치로 남아 있게 된다.\n나는 《검은 집》(2020년)을 시작으로, 《밤의 집》(2021년), 2023년 《기억의 집》, 2024년 5월 13일 전시 예정인 《그 집에 산다》까지 집이라는 장소에 주목하여 작업의 중요 소재로 삼아 왔다.\n나에게 집은 가족과의 정서적 유대감이 충만한 장소이면서도 가족의 부재에서 비롯된 상실감이 혼재된 장소이다. 나의 기억 속 집은 온 가족들이 함께하지 못하고 종종 혼자 지내는 장소이기도 했다. 집 연작들은 이러한 과거의 기억에서 비롯한다. 한 지붕 밑에 온 가족이 모여, 웃고 즐기면서 이야기하는 꿈을 자주 꾸곤 했다.\n《밤의 집》과 《기억의 집》이 집을 정물처럼 근접한 거리에서 정적인 시선으로 접근하여 바라봤다면 이번 《그 집에 산다》는 집들이 함께 어울어져 모여 있는 골목을 중심으로 바라보고자 했다. 서울과 지방을 오고 가며 촬영한 다양한 형태의 집들을 마치 도색 하듯이 색을 입히고, 낡거나 헌 물건을 고치듯이 새롭게 표현하고자 했다. 사람의 온기와 친밀도를 느낄 수 있도록 따뜻한 색조를 많이 사용하고자 했다.\n청소년 시절의 어린 마음에는, 집은 어디에나 있지만, 가족 구성원이 희로애락을 함께 나눌 수 있는 진정한 의미의 집은 어디에도 없을 것으로 생각하곤 했다. 그러나 인간은 기억하고 싶은 것만 기억하듯이 자전적 기억 속의 집은 아름답고 근사한 자태로 그리움으로 남아 있다. 현대인에게도 여전히 인간을 위한 진정한 집은 어디에 있는지, 집은 인간에게 어떤 의미가 있는지, 풀리지 않는 수수께끼처럼 남아 있다.\n청소년기에 겪었던 가족에 대한 그리움과 애틋한 기억과 돌아갈 수 없는 시절의 노스탤지어 감성으로 집의 진정한 의미를 찾아 가는 여정을 통해 이 시대를 살아가는데 필요한 진정한 위안과 집이라는 장소에 깃든 삶의 아름다움과 특별함을 표현하고자 한다.',
    size: '60x50cm',
    material: 'Archival pigment print',
    year: '2024',
    edition: '',
    price: '₩1,500,000',
    image: '13.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/32',
  },
  {
    id: '14',
    artist: '라인석',
    title: '곡선운동의 궤적으로부터 롯데월드타워 230817',
    description: '',
    size: '50x30cm',
    material: 'pigment based inkjet on matte paper',
    year: '2023',
    edition: '',
    price: '₩700,000',
    image: '14.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/33',
  },
  {
    id: '15',
    artist: '라인석',
    title: '서울타워로부터',
    description: '',
    size: '107.5x77.5cm',
    material: 'pigment based inkjet on touched paper, 하얀색 원목액자',
    year: '2019',
    edition: '에디션 1/1',
    price: '₩5,000,000',
    image: '15.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/34',
  },
  {
    id: '16',
    artist: '라인석',
    title: '휘어진 세계로부터_모나미볼펜 1',
    description: '',
    size: '42x58cm',
    material: 'pigment based inkjet on matte paper, 알루미늄 액자',
    year: '2015',
    edition: '',
    price: '₩1,200,000',
    image: '16.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/35',
  },
  {
    id: '17',
    artist: '이호철',
    title: 'The great resurrection (위대한 부활)',
    description: '',
    size: '30호',
    material: 'Acrylic on canvas Acrylic on supermirror',
    year: '',
    edition: '',
    price: '₩6,000,000',
    image: '17.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/36',
  },
  {
    id: '18',
    artist: '이호철',
    title: 'The great resurrection (위대한 부활)',
    description: '',
    size: '',
    material: '',
    year: '',
    edition: '',
    price: '₩7,000,000',
    image: '18.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/37',
  },
  {
    id: '19',
    artist: '이호철',
    title: 'The great resurrection (위대한 부활)',
    description: '',
    size: '',
    material: '',
    year: '',
    edition: '',
    price: '₩8,000,000',
    image: '19.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/38',
  },
  {
    id: '20',
    artist: '심모비',
    title: '9408 SIM_Visibility',
    description:
      '“하나의 생명을 낳는 것은 하나의 죽음을 낳는 것과 같다.”\n생명은 결국 죽음을 맞이할 수밖에 없으며,\n내 생명의 주체인 자신과, 나의 생명을 낳는 주체는\n항상 다른 인물일 수밖에 없다.\n자신이 낳지 않은 자신의 삶을 살아가야 하는 고됨,\n죽음이 다가오는 불안. 그 사이에서 벌어지는 수많은 충돌과 좌절과 허무.\n생과 사가 결정되기 이전의 장소인 연옥을 관찰하게 된 것은 어쩌면\n필연적인 과정이었을지도 모른다.\n삶과 죽음의 굴레에서 벗어나,\n자유롭게 존재할 수 있는 대안 공간을 찾고 있던 나에게,\n연옥이란 나의 먼 과거의 전생과 전생에서부터 이어져온,\n내 곁에 항상 존재했던 곳이었음을.',
    size: '10F (45.5 x 53cm)',
    material: '믹스미디어 이후 아크릴 스틱 콜라주, 아크릴 채색',
    year: '',
    edition: '',
    price: '₩800,000',
    image: '20.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/39',
  },
  {
    id: '21',
    artist: '심모비',
    title: '9409 SIM_Visibility',
    description:
      '“하나의 생명을 낳는 것은 하나의 죽음을 낳는 것과 같다.”\n생명은 결국 죽음을 맞이할 수밖에 없으며,\n내 생명의 주체인 자신과, 나의 생명을 낳는 주체는\n항상 다른 인물일 수밖에 없다.\n자신이 낳지 않은 자신의 삶을 살아가야 하는 고됨,\n죽음이 다가오는 불안. 그 사이에서 벌어지는 수많은 충돌과 좌절과 허무.\n생과 사가 결정되기 이전의 장소인 연옥을 관찰하게 된 것은 어쩌면\n필연적인 과정이었을지도 모른다.\n삶과 죽음의 굴레에서 벗어나,\n자유롭게 존재할 수 있는 대안 공간을 찾고 있던 나에게,\n연옥이란 나의 먼 과거의 전생과 전생에서부터 이어져온,\n내 곁에 항상 존재했던 곳이었음을.',
    size: '10F (45.5 x 53cm)',
    material: '믹스미디어 이후 아크릴 스틱 콜라주, 아크릴 채색',
    year: '',
    edition: '',
    price: '₩800,000',
    image: '21.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/40',
    sold: true,
  },
  {
    id: '22',
    artist: '신학철',
    title: '무제',
    description: '',
    size: '24x35.5cm',
    material: '콜라주',
    year: '1997',
    edition: '',
    price: '₩3,000,000',
    image: '22.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/41',
  },
  {
    id: '23',
    artist: '신학철',
    title: '한국현대사-민주주의 만세(5.18)',
    description: '',
    size: '77.8x53.6cm',
    material: '콜라주',
    year: '2017',
    edition: '',
    price: '₩12,000,000',
    image: '23.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/42',
  },
  {
    id: '24',
    artist: '신학철',
    title: '한국현대사-유월항쟁도(1988)',
    description: '',
    size: '227x90cm',
    material: '목판, 캔버스',
    year: '1988',
    edition: '',
    price: '₩25,000,000',
    image: '24.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/43',
  },
  {
    id: '25',
    artist: '이익태',
    title: '山',
    description: '',
    size: '33x59cm',
    material: '먹, 한지',
    year: '2021',
    edition: '',
    price: '₩1,800,000',
    image: '25.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/44',
    sold: true,
  },
  {
    id: '26',
    artist: '이익태',
    title: 'Beam Letter',
    description: '',
    size: '60x55cm',
    material: 'acrylic, 한지',
    year: '2011',
    edition: '',
    price: '₩3,500,000',
    image: '26.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/45',
  },
  {
    id: '27',
    artist: '이익태',
    title: '시지프스의 연인',
    description: '',
    size: '55x33cm',
    material: 'acrylic, 알루미늄',
    year: '2025',
    edition: '',
    price: '₩2,000,000',
    image: '27.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/46',
  },
  {
    id: '1',
    artist: '신예리',
    title: '취도(鷲圖)',
    description: '',
    size: '111x65cm',
    material: '염색한지 위에 분채',
    year: '2025',
    edition: '',
    price: '₩5,000,000',
    image: '1.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/47',
  },
  {
    id: '28',
    artist: '주재환',
    title: '귀찮아...',
    description: '',
    size: '80x62cm',
    material: '종이에 혼합재료',
    year: '2021',
    edition: '에디션 6/20',
    price: '₩2,300,000',
    image: '28.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/48',
  },
  {
    id: '29',
    artist: '김종환',
    title: '두상연구 - 가르마가 있는 두상1',
    description:
      'statement\n익숙한, 또는 익숙하지 않은......\n형체를 끝까지 남김으로서 그 존재파악에 조금 더 도움을 주고자 친절한 그리기를 행하였다.\n익숙한 형체에 대한 불만족은 점점 커갔고 이것이 화면에서 그대로 재현될 때 굉장히 조잡하게 느껴지거나\n불편해 보이기까지 했다. 그때는 그러했지만 지금은 그렇지가 않아서일까.......\n한번 썼던 물건들을 그냥 쉽게 버린 적이 없다. 고장난 프린터기를 뜯어보니 꽤 괜찮은 부품들이 나왔다.\n몇 개의 모터와 톱니들, 쇠막대들, 이상한 부품들, 쓰다 남은 못들, 쓰다 남은 볼펜들, 이제는 옛것이 되어버린\ncd들, 아이들의 책상 다리, 등....... 그 안에서 각각의 기능이 있었던 부속들은 다시 재조합되고 전혀 새로운\n기능으로 결과물을 생산하거나 그 밑그림이 되어 다시 판화라는 다소 클래식하면서 노동집약적인 이미지들로 재탄생된다.\n작품제작에 사용되는 도구들은 새로운 재료로 만들었다기보다는 이미 만들어진 것들의 집합체이다.\n도구는 내가 모든 것을 제어하여 작업을 하기 보다는 예상치 않은 이미지들과 제어하기 어려운 움직임들을 만들어낸다.\n이런 식의 약간은 복잡하고, 어이없는 과정에 집중하는 것은 예전 작업에서 보여주려 했던 형채(形彩)에 대한 불만에서\n시작되었다고 볼 수 있다.\n강해지기 위해 더욱 많은 것을 치장하고 위장할 수밖에 없는 현실의 부조리처럼 본인이 생소하다고 느껴지는 이미지로\n무장하여 나를 가두는 행위를 반복하였다. 그 틀에서 벗어나고 싶었고 이제는 좀 더 불친절한 구체적이지 않은 형상으로\n화면에서나마 자유로워지고 싶었다.\n\n현재 본인이 쓰고 있는 도구들의 공통점은 multiple이다. 이는 도구의 표현 방식과 판화의 에디션 개념에 대한 공통된 의미이다.\n또한 재활용의 의미도 담고 있다. 이런 익숙하면서도 익숙하지 않은 도구들은 내게 익숙한 판화라는 방식, 드로잉으로 얼굴이라는\n다소 익숙한 이미지로 탄생되어 지지만 그 이미지 조차도 익숙하지 않다. 실험적인 이미지, 방법이라는 의미에서 작품의 부제앞에\n두상연구라는 단어를 붙이는 것이다.\n수년동안 얼굴을 주제로 그리기도 하고 자르기도 하고 찍기도 하였다. 정지된 장면으로 보여지기 보다는 관객에게 무언가를 흔들고\n싶어하는 흐름의 시도였다. 그것은 감정일 것이고 더 나아가 공감일 것이다.\n익숙하지 않거나 익숙한 것에서 파생되는 생소함이 본인의 작업을 처음 봤을 때는 의문으로 다가오지만 이내 감정의 변화가 생기는\n일종의 ‘감정 전이(轉移)’를 추구한다. 이런 의도를 극대화하기 위해 얼굴(두상)이미지로 표현한다.\n얼굴에서 흐르는 에너지는 사방에 존재하는 기운에 영향 받아 시각적 교류를 통해 다시금 관람자에게 전달된다.\n고무판(리놀륨판)을 파고 즉흥적으로 판을 자르고 그 위에 잉크를 올리고 찍는 행위는 이전의 판화과정과 흡사하지만 판화에서의\n에디션 개념을 버리고 한장만 취하는 형식(monotype)으로 제작한다. 얼굴(두상)이라는 큰 틀에서 다양한 모양과 크기의 판(Layer)에\n롤러를 이용해 색을 올리고 찍는다.\n기억과 역사는 진실과 거짓으로 뒤섞여 있다. 기억을 상징하는 조각들은 어떻게 배치되느냐에 따라 결과물이 달라진다. 같은 일을\n경험하더라도 사람들마다 기억되어지는 것이 다르고 기억하고 싶은 부분이 자신에게 유리하거나 이기적인 근본에서 시작된다는 것을\n작품으로 표현하고 있다. 진실한 기억을 상기하고 성찰하는 자세로 살아가고 싶다. 기억을 떠올리기 위해 하나하나 그 기억을 떠올릴\n때 그 조각들이 재배치되고 그 기억으로 인해 다른 기억이 떠올려진다.\n잘한 일 보다는 잘못하거나 가슴 아픈 기억들이 생각난다.\n상기하고 반성하고 앞으로 잘 살아가기 위해 오늘도 노력한다.',
    size: '81.3x88.6cm',
    material: 'Mixed media',
    year: '2024',
    edition: '',
    price: '₩5,000,000',
    image: '29.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/49',
  },
  {
    id: '30',
    artist: '김종환',
    title: '두상연구',
    description:
      'statement\n익숙한, 또는 익숙하지 않은......\n형체를 끝까지 남김으로서 그 존재파악에 조금 더 도움을 주고자 친절한 그리기를 행하였다.\n익숙한 형체에 대한 불만족은 점점 커갔고 이것이 화면에서 그대로 재현될 때 굉장히 조잡하게 느껴지거나\n불편해 보이기까지 했다. 그때는 그러했지만 지금은 그렇지가 않아서일까.......\n한번 썼던 물건들을 그냥 쉽게 버린 적이 없다. 고장난 프린터기를 뜯어보니 꽤 괜찮은 부품들이 나왔다.\n몇 개의 모터와 톱니들, 쇠막대들, 이상한 부품들, 쓰다 남은 못들, 쓰다 남은 볼펜들, 이제는 옛것이 되어버린\ncd들, 아이들의 책상 다리, 등....... 그 안에서 각각의 기능이 있었던 부속들은 다시 재조합되고 전혀 새로운\n기능으로 결과물을 생산하거나 그 밑그림이 되어 다시 판화라는 다소 클래식하면서 노동집약적인 이미지들로 재탄생된다.\n작품제작에 사용되는 도구들은 새로운 재료로 만들었다기보다는 이미 만들어진 것들의 집합체이다.\n도구는 내가 모든 것을 제어하여 작업을 하기 보다는 예상치 않은 이미지들과 제어하기 어려운 움직임들을 만들어낸다.\n이런 식의 약간은 복잡하고, 어이없는 과정에 집중하는 것은 예전 작업에서 보여주려 했던 형채(形彩)에 대한 불만에서\n시작되었다고 볼 수 있다.\n강해지기 위해 더욱 많은 것을 치장하고 위장할 수밖에 없는 현실의 부조리처럼 본인이 생소하다고 느껴지는 이미지로\n무장하여 나를 가두는 행위를 반복하였다. 그 틀에서 벗어나고 싶었고 이제는 좀 더 불친절한 구체적이지 않은 형상으로\n화면에서나마 자유로워지고 싶었다.\n\n현재 본인이 쓰고 있는 도구들의 공통점은 multiple이다. 이는 도구의 표현 방식과 판화의 에디션 개념에 대한 공통된 의미이다.\n또한 재활용의 의미도 담고 있다. 이런 익숙하면서도 익숙하지 않은 도구들은 내게 익숙한 판화라는 방식, 드로잉으로 얼굴이라는\n다소 익숙한 이미지로 탄생되어 지지만 그 이미지 조차도 익숙하지 않다. 실험적인 이미지, 방법이라는 의미에서 작품의 부제앞에\n두상연구라는 단어를 붙이는 것이다.\n수년동안 얼굴을 주제로 그리기도 하고 자르기도 하고 찍기도 하였다. 정지된 장면으로 보여지기 보다는 관객에게 무언가를 흔들고\n싶어하는 흐름의 시도였다. 그것은 감정일 것이고 더 나아가 공감일 것이다.\n익숙하지 않거나 익숙한 것에서 파생되는 생소함이 본인의 작업을 처음 봤을 때는 의문으로 다가오지만 이내 감정의 변화가 생기는\n일종의 ‘감정 전이(轉移)’를 추구한다. 이런 의도를 극대화하기 위해 얼굴(두상)이미지로 표현한다.\n얼굴에서 흐르는 에너지는 사방에 존재하는 기운에 영향 받아 시각적 교류를 통해 다시금 관람자에게 전달된다.\n고무판(리놀륨판)을 파고 즉흥적으로 판을 자르고 그 위에 잉크를 올리고 찍는 행위는 이전의 판화과정과 흡사하지만 판화에서의\n에디션 개념을 버리고 한장만 취하는 형식(monotype)으로 제작한다. 얼굴(두상)이라는 큰 틀에서 다양한 모양과 크기의 판(Layer)에\n롤러를 이용해 색을 올리고 찍는다.\n기억과 역사는 진실과 거짓으로 뒤섞여 있다. 기억을 상징하는 조각들은 어떻게 배치되느냐에 따라 결과물이 달라진다. 같은 일을\n경험하더라도 사람들마다 기억되어지는 것이 다르고 기억하고 싶은 부분이 자신에게 유리하거나 이기적인 근본에서 시작된다는 것을\n작품으로 표현하고 있다. 진실한 기억을 상기하고 성찰하는 자세로 살아가고 싶다. 기억을 떠올리기 위해 하나하나 그 기억을 떠올릴\n때 그 조각들이 재배치되고 그 기억으로 인해 다른 기억이 떠올려진다.\n잘한 일 보다는 잘못하거나 가슴 아픈 기억들이 생각난다.\n상기하고 반성하고 앞으로 잘 살아가기 위해 오늘도 노력한다.',
    size: '108x78cm',
    material: 'Etching, Drypoint',
    year: '2018',
    edition: '',
    price: '₩2,000,000',
    image: '30.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/50',
  },
  {
    id: '31',
    artist: '김종환',
    title: '두상연구-거인의 초상',
    description:
      'statement\n익숙한, 또는 익숙하지 않은......\n형체를 끝까지 남김으로서 그 존재파악에 조금 더 도움을 주고자 친절한 그리기를 행하였다.\n익숙한 형체에 대한 불만족은 점점 커갔고 이것이 화면에서 그대로 재현될 때 굉장히 조잡하게 느껴지거나\n불편해 보이기까지 했다. 그때는 그러했지만 지금은 그렇지가 않아서일까.......\n한번 썼던 물건들을 그냥 쉽게 버린 적이 없다. 고장난 프린터기를 뜯어보니 꽤 괜찮은 부품들이 나왔다.\n몇 개의 모터와 톱니들, 쇠막대들, 이상한 부품들, 쓰다 남은 못들, 쓰다 남은 볼펜들, 이제는 옛것이 되어버린\ncd들, 아이들의 책상 다리, 등....... 그 안에서 각각의 기능이 있었던 부속들은 다시 재조합되고 전혀 새로운\n기능으로 결과물을 생산하거나 그 밑그림이 되어 다시 판화라는 다소 클래식하면서 노동집약적인 이미지들로 재탄생된다.\n작품제작에 사용되는 도구들은 새로운 재료로 만들었다기보다는 이미 만들어진 것들의 집합체이다.\n도구는 내가 모든 것을 제어하여 작업을 하기 보다는 예상치 않은 이미지들과 제어하기 어려운 움직임들을 만들어낸다.\n이런 식의 약간은 복잡하고, 어이없는 과정에 집중하는 것은 예전 작업에서 보여주려 했던 형채(形彩)에 대한 불만에서\n시작되었다고 볼 수 있다.\n강해지기 위해 더욱 많은 것을 치장하고 위장할 수밖에 없는 현실의 부조리처럼 본인이 생소하다고 느껴지는 이미지로\n무장하여 나를 가두는 행위를 반복하였다. 그 틀에서 벗어나고 싶었고 이제는 좀 더 불친절한 구체적이지 않은 형상으로\n화면에서나마 자유로워지고 싶었다.\n\n현재 본인이 쓰고 있는 도구들의 공통점은 multiple이다. 이는 도구의 표현 방식과 판화의 에디션 개념에 대한 공통된 의미이다.\n또한 재활용의 의미도 담고 있다. 이런 익숙하면서도 익숙하지 않은 도구들은 내게 익숙한 판화라는 방식, 드로잉으로 얼굴이라는\n다소 익숙한 이미지로 탄생되어 지지만 그 이미지 조차도 익숙하지 않다. 실험적인 이미지, 방법이라는 의미에서 작품의 부제앞에\n두상연구라는 단어를 붙이는 것이다.\n수년동안 얼굴을 주제로 그리기도 하고 자르기도 하고 찍기도 하였다. 정지된 장면으로 보여지기 보다는 관객에게 무언가를 흔들고\n싶어하는 흐름의 시도였다. 그것은 감정일 것이고 더 나아가 공감일 것이다.\n익숙하지 않거나 익숙한 것에서 파생되는 생소함이 본인의 작업을 처음 봤을 때는 의문으로 다가오지만 이내 감정의 변화가 생기는\n일종의 ‘감정 전이(轉移)’를 추구한다. 이런 의도를 극대화하기 위해 얼굴(두상)이미지로 표현한다.\n얼굴에서 흐르는 에너지는 사방에 존재하는 기운에 영향 받아 시각적 교류를 통해 다시금 관람자에게 전달된다.\n고무판(리놀륨판)을 파고 즉흥적으로 판을 자르고 그 위에 잉크를 올리고 찍는 행위는 이전의 판화과정과 흡사하지만 판화에서의\n에디션 개념을 버리고 한장만 취하는 형식(monotype)으로 제작한다. 얼굴(두상)이라는 큰 틀에서 다양한 모양과 크기의 판(Layer)에\n롤러를 이용해 색을 올리고 찍는다.\n기억과 역사는 진실과 거짓으로 뒤섞여 있다. 기억을 상징하는 조각들은 어떻게 배치되느냐에 따라 결과물이 달라진다. 같은 일을\n경험하더라도 사람들마다 기억되어지는 것이 다르고 기억하고 싶은 부분이 자신에게 유리하거나 이기적인 근본에서 시작된다는 것을\n작품으로 표현하고 있다. 진실한 기억을 상기하고 성찰하는 자세로 살아가고 싶다. 기억을 떠올리기 위해 하나하나 그 기억을 떠올릴\n때 그 조각들이 재배치되고 그 기억으로 인해 다른 기억이 떠올려진다.\n잘한 일 보다는 잘못하거나 가슴 아픈 기억들이 생각난다.\n상기하고 반성하고 앞으로 잘 살아가기 위해 오늘도 노력한다.',
    size: '100x70cm',
    material: 'Lithography',
    year: '2018',
    edition: '',
    price: '₩2,000,000',
    image: '31.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/51',
  },
  {
    id: '32',
    artist: '이철수',
    title: '무문관 50장(연작판화)',
    description: '',
    size: '',
    material: '목판, 한지',
    year: '2021',
    edition: '',
    price: '₩50,000,000',
    image: '32.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/52',
  },
  {
    id: '33',
    artist: '이수철',
    title: 'Over the Dream-2',
    description: '',
    size: '50x50cm',
    material: '',
    year: '2011',
    edition: '에디션 5/5',
    price: '₩1,000,000',
    image: '33.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/53',
  },
  {
    id: '34',
    artist: '이호철',
    title: 'The great resurrection (위대한 부활)',
    description: '',
    size: '',
    material: '',
    year: '',
    edition: '',
    price: '₩6,000,000',
    image: '34.png',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/54',
  },

  {
    id: '36',
    artist: '김준권',
    title: '수묵',
    description: '',
    size: '60x45cm',
    material: '채묵목판',
    year: '2021',
    edition: '',
    price: '₩7,000,000',
    image: '36.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/56',
  },
  {
    id: '37',
    artist: '김준권',
    title: '푸른 소나무',
    description: '',
    size: '45x80cm',
    material: '유성목판',
    year: '2023',
    edition: '',
    price: '₩7,000,000',
    image: '37.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/57',
  },
  {
    id: '38',
    artist: '김준권',
    title: '소나무',
    description: '',
    size: '18x22cm',
    material: '유성목판',
    year: '2023',
    edition: '',
    price: '₩500,000',
    image: '38.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/58',
    sold: true,
  },
  {
    id: '39',
    artist: '김준권',
    title: 'Blue Night-1',
    description: '',
    size: '22x18cm',
    material: '유성목판',
    year: '2025',
    edition: '',
    price: '₩500,000',
    image: '39.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/59',
    sold: true,
  },
  {
    id: '40',
    artist: '한애규',
    title: '달을 든 여인',
    description: '',
    size: '',
    material: '테라코타',
    year: '2021',
    edition: '',
    price: '₩2,000,000',
    image: '40.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/60',
    sold: true,
  },
  {
    id: '41',
    artist: '심현희',
    title: '사소한 일상',
    description: '',
    size: '35x28cm',
    material: '캔버스에 아크릴',
    year: '2022',
    edition: '',
    price: '₩2,500,000',
    image: '41.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/61',
  },
  {
    id: '42',
    artist: '류준화',
    title: '책의 무게',
    description: '',
    size: '45.5x38cm',
    material: '캔버스에 아크릴',
    year: '2023',
    edition: '',
    price: '₩2,800,000',
    image: '42.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/62',
  },
  {
    id: '43',
    artist: '최경선',
    title: '날마다',
    description: '',
    size: '53x41.2cm',
    material: 'Oil on canvas',
    year: '2022',
    edition: '',
    price: '₩2,800,000',
    image: '43.jpg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/63',
  },
  {
    id: '44',
    artist: '김주호',
    title: '내 손끝에 은하수',
    description: '',
    size: '',
    material: '질구이',
    year: '2020',
    edition: '',
    price: '₩3,000,000',
    image: '44.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/64',
  },
  {
    id: '45',
    artist: '김상구',
    title: 'No 895',
    description: '',
    size: '180x30cm',
    material: '한지에 목판화',
    year: '2005',
    edition: '',
    price: '₩4,000,000',
    image: '45.png',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/65',
  },
  {
    id: '46',
    artist: '류연복',
    title: '북한산을 거닐다-2',
    description: '',
    size: '38x165cm',
    material: '한지에 목판화',
    year: '2013',
    edition: '',
    price: '₩4,000,000',
    image: '46.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/66',
  },
  {
    id: '47',
    artist: '이윤엽',
    title: '튼튼한 감나무',
    description: '',
    size: '56x76cm',
    material: '',
    year: '2025',
    edition: '',
    price: '₩1,000,000',
    image: '47.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/67',
  },
  {
    id: '48',
    artist: '이윤엽',
    title: '북한산 2025',
    description: '',
    size: '56x76cm',
    material: '',
    year: '2025',
    edition: '',
    price: '₩1,000,000',
    image: '48.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/68',
  },
  {
    id: '49',
    artist: '이윤엽',
    title: '행복한 나날 2020',
    description: '',
    size: '56x76cm',
    material: '',
    year: '2020',
    edition: '',
    price: '₩1,000,000',
    image: '49.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/69',
  },
  {
    id: '50',
    artist: '이윤엽',
    title: '나를 안는다',
    description: '',
    size: '30x42cm',
    material: '',
    year: '2025',
    edition: '',
    price: '₩500,000',
    image: '50.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/70',
  },
  {
    id: '51',
    artist: '이윤엽',
    title: '붉은 봄 매화',
    description: '',
    size: '41x41cm',
    material: '',
    year: '2018',
    edition: '',
    price: '₩700,000',
    image: '51.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/71',
  },
  {
    id: '55',
    artist: '정미정',
    title: '그곳',
    description: '',
    size: '72.7x53cm',
    material: 'Oil on canvas',
    year: '2022',
    edition: '',
    price: '₩3,000,000',
    image: '55.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/75',
    sold: true,
  },
  {
    id: '56',
    artist: '정미정',
    title: '그곳',
    description: '',
    size: '72.7x53cm',
    material: 'Oil on canvas',
    year: '2022',
    edition: '',
    price: '₩3,000,000',
    image: '56.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/76',
    sold: true,
  },
  {
    id: '57',
    artist: '최재란',
    title: '쿼크의 시간#111',
    description:
      '‘쿼크(Quark)’는 입자물리학의 표준모형에 따르면 원자핵의 양성자나 중성자의 구성요소이자 기본 입자로 우주를 구성하는 가장 근본적인 입자이다. 우리의 일상, 매일 바라보는 세상에서 매순간 경험하고 느끼지만 볼 수 없는 시간을 물리에서 설명하는 시간을 차용한 <쿼크의 시간>은 매일 산책하면서 떨어진 자연물을 줍거나 채집하여 정물적 구성을 한 후 우주에 흐르는 보이지 않는 시간을 상징적으로 드로잉하여 시간의 방향성을 표현한 작업이다.\n예부터 우리는 자연의 세계를 통해 생명의 근원, 삶의 이치를 성찰하고 자연에 순응하며 존중하는 겸허한 자세로 살아가고자 하였다. <쿼크(Quark)의 시간>은 시간의 흐름에 따라 시들고 소멸하는 변화하는 자연이 인간의 생로병사(生老病死)와 닮아 있음을 느끼며 산책길에 떨어지고 스러져가는 꽃잎, 열매, 작은 씨앗들을 줍거나 채집하고 재조합하여 밤하늘과 무한한 우주의 시간을 상상하며 정물(Still Life)적 구성을 한 후 우주, 별자리, 물리에서의 시간, 전통문양을 드로잉 하여 시간의 방향성을 표현하고자 하였다.\n작업방식은 매일 산책하면서 자연물을 탐색한 후 계절마다 변화하는 시들거나 소멸하는 자연물을 줍고 채집하여 검은 배경을 밤하늘과 무한한 우주를 상상하며 시들어가는 자연물을 와이어에 매달고, 씨앗과 열매를 붙이고, 스러지는 것들을 핀으로 고정시키는 등 재조합하여 자연의 본질을 정물(Still Life)로 표현한 후 별자리, 우주, 물리에서의 시간, 전통문양을 상징적으로 드로잉하여 시간의 흐름을 표현하였다.\n고대부터 별은 위대한 사람의 탄생이나 죽음의 일화로 전해지고 사후세계의 일면으로 간주하였으며 별의 움직임은 계절과 시간의 흐름을 가르쳐주었다. 경외(敬畏)와 관심, 매혹의 대상이었다. 나는 정물(Still Life)들이 나의 우주안에 빛나는 별이 되기를 바라며 별자리를 드로잉하였다. 또한 선사시대의 바위그림에는 그 시대의 우주관과 신앙, 의식행위를 살펴 볼 수 있으며 우리나라 칠보무늬는 자손들에게 기쁜 일이 많이 일어나고 풍요로운 삶과 만사가 형통하기를 바라며 장신구, 도자기등 여러 기물에 베풀어졌다. 우주의 섭리가 깃든 고대문양과 전통문양인 칠보무늬 등을 차용하여 재해석된 문양으로 드로잉하여 시간의 흐름과 시간의 연속성을 부여하고 영원하기를 기원하는 마음을 표현하고자 하였다.\n<쿼크(Quark)의 시간>은 삶과 죽음이 혼재되어 있는 정물(Still Life)적 구성을 통해 존재하는 모든 것들은 유한한 시간성안에 살아가고 있음을 은유하여 스러져가는 자연물을 정물적 구성과 드로잉을 의식(ritual)처럼 행함으로써 애도하는 마음과 나의 우주안에서 영원하길 바라는 간절한 마음을 표현하였다. 또한 유한한 시간을 살아가고 있는 우리는 태어나서 한 방향을 향해 가고 있는데 어디로 가고 있는지 질문하고자 하였다. 이 질문을 통해 나의 존재, 삶의 의미를 생각해 보는 시간이 되었으면 한다. 다음 작업은 쿼크의 시간 바다시리즈로 바다에서 주워온 파도의 시간에 의해 닳은 작은 조각들을 정물적 구성과 드로잉으로 시간의 방향성을 풀어내고자 한다.',
    size: '100x100cm',
    material: 'Archival pigment print',
    year: '2024',
    edition: '',
    price: '₩3,000,000',
    image: '57.png',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/77',
  },
];
