import { Artwork } from '@/types';

export const batch007: Artwork[] = [
  {
    id: '248',
    artist: '천지수',
    title: '다른 세계와의 교감',
    description: '',
    size: '90.9x72.7cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩3,600,000',
    image: '248.png',
  },
  {
    id: '249',
    artist: '천지수',
    title: '정글의 대화',
    description: '',
    size: '73x61cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩2,400,000',
    image: '249.png',
  },
  {
    id: '250',
    artist: '천지수',
    title: '아프리카 커피의 기억',
    description: '',
    size: '65.5x53cm',
    material: 'mixed media on canvas',
    year: '2024',
    edition: '',
    price: '₩1,800,000',
    image: '250.png',
  },
  {
    id: '251',
    artist: '천지수',
    title: '가족 family',
    description: '',
    size: '27x27cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩650,000',
    image: '251.png',
  },
  {
    id: '252',
    artist: '류호식',
    title: 'Naturance',
    description: `류호식 작가의 작품들은 부조리한 현실과 그 안에서 의미를 찾고자 하는 정서를 표명한다. 주로 자연에서 영감을 받는 그는 그 순간들의 소중함을 기록한다. 작가는 과거의 어둠을 통해 새로운 희망과 행복을 발견하며, 일상의 이상적인 순간을 간직하고자 하는 소망에서 작품을 제작한다. 류호식 작가는 '페이퍼클레이 페인팅' 기법을 사용한다. 1250도의 가마에서 소성되어 나온 작품들은 류호식 작가 작품 특유의 질감을 만들어낸다.`,
    size: '73x53cm',
    material: '흙 구운 후에 색칠',
    year: '2021',
    edition: '',
    price: '₩300,000',
    image: '252.png',
  },
  {
    id: '253',
    artist: '김지영',
    title: '순 돋는 나무',
    description: '',
    size: '26x26cm',
    material: '도자',
    year: '2016',
    edition: '',
    price: '₩200,000',
    image: '253.png',
  },
  {
    id: '254',
    artist: '김지영',
    title: '잎파리',
    description: '',
    size: '22x15.4cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩100,000',
    image: '254.png',
  },
  {
    id: '255',
    artist: '김태희',
    title: '각진 병',
    description: '',
    size: '27x22.5cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩150,000',
    image: '255.png',
  },
  {
    id: '256',
    artist: '김정원',
    title: '손 모은 사람',
    description: '',
    size: '25.4x19.2cm',
    material: '확인 중',
    year: '확인 중',
    edition: '',
    price: '₩100,000',
    image: '256.png',
  },
  {
    id: '257',
    artist: '한애규',
    title: '무제',
    description: '',
    size: '19x14x2cm',
    material: '흙으로 빗어 굽고 색칠',
    year: '2020',
    edition: '',
    price: '₩2,000,000',
    image: '257.png',
  },
  {
    id: '258',
    artist: '민병산',
    title: '수하석상',
    description: `민병산(閔炳山, 1928~1990) 작가는 '거리의 철학자', '한국의 디오게네스'로 불린 충북 청주 출신의 문필가, 서예가로, 자유분방한 삶과 독특한 '민병산체' 서체, 그리고 '철학의 즐거움' 같은 산문집으로 알려져 있으며, 세속을 초월한 삶을 실천했던 예술가다.`,
    size: '135.3x24cm',
    material: '종이에 먹',
    year: '1986',
    edition: '',
    price: '₩5,000,000',
    image: '258.png',
  },
  {
    id: '259',
    artist: '하선영',
    title: 'Hope 013',
    description: `하선영은 홍익대학교에서 회화를 전공한 후 프랑스 아를국립사진학교에서 사진을 전공하였다. 나무의 초상화 작업과, 이후 팬데믹 시대의 힘겨운 사람들에게 아름다운 세계의 자연을 소재로 한 작품으로 우리에게 위안을 주는 작업을 계속하고 있다.`,
    size: '57x76cm',
    material: 'wax pastel on paper',
    year: '2021',
    edition: '',
    price: '₩1,200,000',
    image: '259.png',
  },
  {
    id: '260',
    artist: '류준화',
    title: '녹색발',
    description: '',
    size: '72.7x60.6cm',
    material: '캔버스위에 아크릴, 콘테, 석회',
    year: '2015',
    edition: '',
    price: '₩5,000,000',
    image: '260.png',
  },
  {
    id: '261',
    artist: '정재철',
    title: 'Middle ground',
    description: '',
    size: '73x53cm',
    material: 'oil on canvas',
    year: '2021',
    edition: '',
    price: '₩3,000,000',
    image: '261.png',
  },
  {
    id: '262',
    artist: '정희진',
    title: 'folded tint',
    description: '',
    size: '61x61cm',
    material: 'acrylic, gouache, gel on modeling made canvas',
    year: '2021',
    edition: '',
    price: '₩3,000,000',
    image: '262.png',
  },
  {
    id: '263',
    artist: '김주희',
    title: '월정교',
    description: `고대 이래로 미술은 정지되어 있는 상을 표현하였다. 한 순간의 시간을 표현한 인상주의에서 절정에 다다랐고, 미래파에 이르러서는 움직이는 물체를 온전하게 표현하고자 하는 시도가 행해진다. 이렇게 시간에 대한 연구는 작가들에게 중요한 과제였다. 작가는 오버랩의 효과를 이용하여 사물과 풍경의 시간을 중첩시키고 펼쳐 보인다. 하지만 여기서 작가의 욕망이 발현되는데, 단순히 시간만이 아닌 작가의 기억까지 오버랩하여 본인의 아이덴티티를 완성한다.`,
    size: '31.8x31.8cm',
    material: 'oil on canvas',
    year: '2020',
    edition: '',
    price: '₩500,000',
    image: '263.png',
  },
  {
    id: '264',
    artist: '김주희',
    title: '제주 섭지코지',
    description: `고대 이래로 미술은 정지되어 있는 상을 표현하였다. 한 순간의 시간을 표현한 인상주의에서 절정에 다다랐고, 미래파에 이르러서는 움직이는 물체를 온전하게 표현하고자 하는 시도가 행해진다. 이렇게 시간에 대한 연구는 작가들에게 중요한 과제였다. 작가는 오버랩의 효과를 이용하여 사물과 풍경의 시간을 중첩시키고 펼쳐 보인다. 하지만 여기서 작가의 욕망이 발현되는데, 단순히 시간만이 아닌 작가의 기억까지 오버랩하여 본인의 아이덴티티를 완성한다.`,
    size: '53x33.3cm',
    material: 'oil on canvas',
    year: '2019',
    edition: '',
    price: '₩1,000,000',
    image: '264.png',
  },
  {
    id: '265',
    artist: '김주호',
    title: '사랑만들기',
    description: '',
    size: '33x20x9cm',
    material: '조각 철판 8T',
    year: '2013',
    edition: '',
    price: '₩1,000,000',
    image: '265.png',
  },
  {
    id: '266',
    artist: '김유진',
    title: '폭발의 다음',
    description: '',
    size: '26x18cm',
    material: 'paint on paper',
    year: '2021',
    edition: '',
    price: '₩200,000',
    image: '266.png',
  },
  {
    id: '267',
    artist: '고자영',
    title: '이동식 정원 69-사라지는 3',
    description: '',
    size: '60x60cm',
    material: '캔버스에 유채, 아크릴채색',
    year: '2012',
    edition: '',
    price: '₩3,000,000',
    image: '267.png',
  },
  {
    id: '268',
    artist: '고현주',
    title: '기억의 목소리',
    description: `1964년 서귀포에서 난 고현주 작가는 2008년부터 안양소년원 아이들에게 사진 찍기를 가르치며 삶의 희망을 전하는 ‘꿈꾸는 카메라' 작업을 했다. 2016년 암 선고를 받고 2년 후인 2018년부터 제주 4·3 사건 체험자들의 기억을 기록하는 작업을 해 그 결과물이 허은실씨가 글을 쓴 책 <기억의 목소리: 사물에 스민 제주 4·3 이야기>(문학동네)로 나왔고, 제8회 고정희상을 받았다.`,
    size: '11x40inch',
    material: 'Archival Pigment print / Hahnemuhle William Turner (Edition 54/100)',
    year: '2021',
    edition: '',
    price: '₩300,000',
    image: '268.png',
  },
  {
    id: '269',
    artist: '최연택',
    title: '풀',
    description: `최연택 작가는 화가, 도예 디자이너, 작가로 활동하며, 특히 그림과 글을 결합한 에세이, 동화책 삽화, 도자기 디자인 등 다양한 분야에서 활동하는 다재다능한 예술가다. 주요 작품으로는 『하루를 더 살기로 했다』, 『무정』 등의 삽화 작업이 있으며, 과거 청와대 식기 디자인에 참여하고 신영복 선생님과 작업하는 등 폭넓은 이력을 가졌다.`,
    size: '37.9x45.5cm',
    material: '천위에 유채',
    year: '2025',
    edition: '',
    price: '₩1,800,000',
    image: '269.png',
  },
  {
    id: '270',
    artist: '박불똥',
    title: '멸(滅)',
    description: `1956년 경상남도 하동에서 태어났고, 홍익대학교에서 서양화를 공부했다. 추상화풍의 미술교육에 염증을 느낀 그는 대신, 사회 참여 예술을 지향하는 미술인 동인 ‘현실과 발언’의 멤버가 되어 활발한 활동을 펼친다. 1985년 박불똥은 《한국미술, 20대의 힘》 전시를 기획하고 작품을 출품하였으나 경찰에 의해 전시가 문을 닫게 되었는데, 이는 한국미술사에서 공권력에 의해 강제로 막을 내린 첫 번째 전시로 기록되고 있다. 사진을 개념적으로 접근하는 포토몽타주 작업에서 탁월한 성과를 내기도 했으며, 쿠바의 아바나비엔날레, 광주비엔날레를 비롯해서 국내외 크고 작은 무수한 단체전에 참여하였으며, 2012년까지 11번의 개인전을 갖기도 했다.`,
    size: '40.7x58.5cm',
    material: '디지털 프린트',
    year: '1992',
    edition: '',
    price: '₩300,000',
    image: '270.png',
  },
  {
    id: '271',
    artist: '이동구',
    title: '사과',
    description: '',
    size: '9x9cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩70,000',
    image: '271.png',
  },
  {
    id: '272',
    artist: '김남진',
    title: '누드',
    description: `김남진(金南鎭)은 1957년 충남 공주 출생으로 고려대를 졸업했다.\n1987년 파인힐 갤러리에서 개인전 '이태원의 밤'과 1993년 바탕골예술관에서 '폴라로이드 누드'전을 가진 바 있다.\n그가 1984년부터 시도한 일련의 '이태원의 밤' 다큐먼트는 성공한 한국사진의 자생적 형식 실험의 하나로 평가받고 있다.\n이후 폴라 컬러의 이미지 전사를 이용한 누드 사진의 새로운 표현양식을 실험하였고,\n1987년부터는 김남진 사진공방을 운영하며 현대사진의 제경향과 이론 그리고 사진미학을 체계화하여 국내에 소개하고 많은 후배 사진가들을 양성하였다.\n\n전시기획자로서 서울국제사진페스티벌과 충무로사진축제를 기획•진행한 바 있으며, 현재 사진문화포럼과 갤러리 브레송의 대표로 있다.`,
    size: '확인 중',
    material: '1/5 프린트',
    year: '1992',
    edition: '에디션 1/5',
    price: '₩500,000',
    image: '272.png',
  },
  {
    id: '273',
    artist: '박생광',
    title: '백두산 천지 아침',
    description: `평생을 일본풍의 그림을 그리는 화가로 살았지만, 생애 마지막 8년 동안 놀랍고도 대담한 예술적 변신을 성공해냈다. 토함산 해돋이, 탈, 단군, 십장생, 창, 불상, 단청, 부적, 무당 등 지극히 한국적인 주제를 선택해서, 수묵화에 강렬한 오방색의 채색을 혼합하는 독창적인 기법을 선보였다. 강렬한 색채와 자유로운 화면구성을 통해, 한국의 토속적인 정서와 민족성이 마치 들끓어 오르는 생명력으로 다가온다. 한국현대미술사의 새롭고도 독창적인 장르를 구축해낸, 수묵채색화의 거장으로 평가받고 있다.`,
    size: '25.7x18.8cm',
    material: '종이, 연필',
    year: '확인 중',
    edition: '',
    price: '₩2,000,000',
    image: '273.png',
  },
  {
    id: '274',
    artist: '이동구',
    title: '보리술잔',
    description: '',
    size: '12.7x10.7cm',
    material: '확인 중',
    year: '확인 중',
    edition: '',
    price: '₩30,000',
    image: '274.png',
  },
];
