import { Artwork } from '@/types';

export const batch006: Artwork[] = [
  {
    id: '228',
    artist: '한미영',
    title: '연인',
    description: '',
    size: '90.9x65.1cm',
    material: 'mixed media on canvas (acrylic, gold leaf, )',
    year: '2024',
    edition: '',
    price: '₩800,000',
    images: ['228.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/364',
  },
  {
    id: '229',
    artist: '한미영',
    title: 'Free will',
    description: '',
    size: '72.7x53.0cm',
    material: 'mixed media on canvas (acrylic, gold leaf, wax paint)',
    year: '2024',
    edition: '',
    price: '₩550,000',
    images: ['229.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/365',
  },
  {
    id: '230',
    artist: '양순열',
    title: 'Ottogi Chrome Rainbow (purple top)',
    description: '',
    size: '60x60x130cm',
    material: 'Car paint on resin',
    year: '2022',
    edition: '',
    price: '₩35,000,000',
    images: ['230.jpg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/366',
  },
  {
    id: '231',
    artist: '양순열',
    title: 'Ottogi Chrome Rainbow (blue top)',
    description: '',
    size: '60x60x130cm',
    material: 'Car paint on resin',
    year: '2022',
    edition: '',
    price: '₩35,000,000',
    images: ['231.jpg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/367',
  },
  {
    id: '232',
    artist: '양순열',
    title: 'Ottogi Earthy Rainbow',
    description: '',
    size: '40x40x90cm',
    material: 'Car paint on resin',
    year: '2021',
    edition: '',
    price: '₩18,500,000',
    images: ['232.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/368',
  },
  {
    id: '233',
    artist: '양순열',
    title: 'Ottogi Earthy Rainbow Matte',
    description: '',
    size: '40x40x65cm',
    material: 'Car paint on resin',
    year: '2021',
    edition: '',
    price: '₩12,600,000',
    images: ['233.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/369',
    sold: true,
  },
  {
    id: '234',
    artist: '양순열',
    title: 'Ottogi_Mother Ya-ho',
    description: '',
    size: '55x55x120cm',
    material: 'Car paint on resin',
    year: '2014',
    edition: '',
    price: '₩25,000,000',
    images: ['234.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/370',
  },
  {
    id: '235',
    artist: '이윤엽',
    title: '무슨일 있어?',
    description: '',
    size: '9.5x14cm',
    material: '확인 중',
    year: '2022',
    edition: '',
    price: '₩200,000',
    images: ['235.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/371',
  },
  {
    id: '236',
    artist: '이윤엽',
    title: '좋은소식',
    description: '',
    size: '27x39.5cm',
    material: '다색목판 48장 중에서',
    year: '2025',
    edition: '',
    price: '₩500,000',
    images: ['236.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/372',
  },
  {
    id: '237',
    artist: '이윤엽',
    title: '새로운 날',
    description: '',
    size: '26.5x80.4cm',
    material: '다색목판',
    year: '확인 중',
    edition: '',
    price: '₩1,000,000',
    images: ['237.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/373',
  },
  {
    id: '238',
    artist: '이윤엽',
    title: '콩밭메는 할머니2',
    description: '',
    size: '25x32.5cm',
    material: '다색목판 60장 중에서',
    year: '2009',
    edition: '',
    price: '₩400,000',
    images: ['238.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/374',
  },
  {
    id: '239',
    artist: '강석태',
    title: '나의 어린 왕자',
    description: '',
    size: '45x45cm',
    material: '캔버스에 아크릴채색',
    year: '2025',
    edition: '',
    price: '₩1,800,000',
    images: ['239.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/375',
  },
  {
    id: '240',
    artist: '강석태',
    title: '함께하는 시간',
    description: '',
    size: '40.9x31.8cm',
    material: '장지에 아크릴 채색',
    year: '2025',
    edition: '',
    price: '₩1,000,000',
    images: ['240.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/376',
    sold: true,
  },
  {
    id: '241',
    artist: '강석태',
    title: '언제나 내 곁에',
    description: '',
    size: '72.7x60.6cm',
    material: '캔버스에 아크릴채색',
    year: '2022',
    edition: '',
    price: '₩3,600,000',
    images: ['241.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/377',
    sold: true,
  },
  {
    id: '242',
    artist: '강석태',
    title: '어린 왕자의 별',
    description: '',
    size: '45x90cm',
    material: '캔버스에 아크릴채색',
    year: '2023',
    edition: '',
    price: '₩2,600,000',
    images: ['242.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/378',
  },
  {
    id: '243',
    artist: '강석태',
    title: '너에게로 가는 바람',
    description: '',
    size: '65x53cm',
    material: '캔버스에 아크릴채색',
    year: '2025',
    edition: '',
    price: '₩2,700,000',
    images: ['243.jpg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/379',
    sold: true,
  },
  {
    id: '244',
    artist: '이문형',
    title: '책거리x크리스마스',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    images: ['244.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/380',
  },
  {
    id: '245',
    artist: '이문형',
    title: '책거리x앙리 마티스',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    images: ['245.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/381',
    sold: true,
  },
  {
    id: '246',
    artist: '이문형',
    title: '책거리x쿠사마야요이',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    images: ['246.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/382',
  },
  {
    id: '247',
    artist: '이문형',
    title: '책거리x살바도르 달리',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    images: ['247.jpeg'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/383',
  },
];
