import { Artwork } from '@/types';

export const batch008: Artwork[] = [
  {
    id: '276',
    artist: '손장섭',
    title: '겨울항구',
    description: '',
    size: '확인 중',
    material: '종이에 유채',
    year: '2010',
    edition: '',
    price: '₩15,000,000',
    image: '276.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/416',
  },
  {
    id: '277',
    artist: '김정원',
    title: '손 모은 사람',
    description: '',
    size: '25.4x19.2cm',
    material: '확인 중',
    year: '확인 중',
    edition: '',
    price: '₩100,000',
    image: '277.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/417',
  },
  {
    id: '278',
    artist: '이열',
    title: '기억의 푸른 바오밥',
    description: '',
    size: 'A4 size',
    material: 'hahnemuhle Baryta FB, pigment ink-jet print',
    year: '확인 중',
    edition: '',
    price: '₩150,000',
    image: '278.jpeg',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/418',
    sold: true,
  },
  {
    id: '279',
    artist: '박생광',
    title: '쏘가리',
    description: '',
    size: '25x18cm',
    material: '종이에 연필',
    year: '1950',
    edition: '',
    price: '₩2,000,000',
    image: '279.png',
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/419',
  },
];
