import { Artwork } from '@/types';

export const batch007: Artwork[] = [
  {
    id: '248',
    artist: '천지수',
    title: '다른 세계와의 교감',
    description: '',
    size: '90.9x72.7cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩3,600,000',
    images: ['248.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/384',
    sold: true,
  },
  {
    id: '249',
    artist: '천지수',
    title: '정글의 대화',
    description: '',
    size: '73x61cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩2,400,000',
    images: ['249.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/385',
  },
  {
    id: '250',
    artist: '천지수',
    title: '아프리카 커피의 기억',
    description: '',
    size: '65.5x53cm',
    material: 'mixed media on canvas',
    year: '2024',
    edition: '',
    price: '₩1,800,000',
    images: ['250.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/386',
  },
  {
    id: '251',
    artist: '천지수',
    title: '가족 family',
    sold: true,
    description: '',
    size: '27x27cm',
    material: 'oil on canvas',
    year: '2025',
    edition: '',
    price: '₩650,000',
    images: ['251.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/387',
  },
  {
    id: '252',
    artist: '류호식',
    title: 'Naturance',
    description: '',
    size: '73x53cm',
    material: '흙 구운 후에 색칠',
    year: '2021',
    edition: '',
    price: '₩300,000',
    images: ['252.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/388',
    sold: true,
  },
  {
    id: '253',
    artist: '김지영',
    title: '순 돋는 나무',
    description: '',
    size: '26x26cm',
    material: '도자',
    year: '2016',
    edition: '',
    price: '₩200,000',
    images: ['253.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/389',
    sold: true,
  },
  {
    id: '254',
    artist: '김지영',
    title: '잎파리',
    description: '',
    size: '22x15.4cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩100,000',
    images: ['254.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/390',
    sold: true,
  },
  {
    id: '255',
    artist: '김태희',
    title: '각진 병',
    description: '',
    size: '27x22.5cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩300,000',
    images: ['255.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/391',
  },
  {
    id: '256',
    artist: '김정원',
    title: '손 모은 사람',
    description: '',
    size: '25.4x19.2cm',
    material: '확인 중',
    year: '확인 중',
    edition: '',
    price: '₩100,000',
    images: ['256.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/392',
    sold: true,
  },
  {
    id: '257',
    artist: '한애규',
    title: '무제',
    description: '',
    size: '19x14x2cm',
    material: '흙으로 빗어 굽고 색칠',
    year: '2020',
    edition: '',
    price: '₩2,000,000',
    images: ['257.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/393',
    sold: true,
  },
  {
    id: '258',
    artist: '민병산',
    title: '수하석상',
    description: '',
    size: '135.3x24cm',
    material: '종이에 먹',
    year: '1986',
    edition: '',
    price: '₩5,000,000',
    images: ['258.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/394',
  },
  {
    id: '259',
    artist: '하선영',
    title: 'Hope 013',
    description: '',
    size: '57x76cm',
    material: 'wax pastel on paper',
    year: '2021',
    edition: '',
    price: '₩1,200,000',
    images: ['259.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/395',
  },
  {
    id: '260',
    artist: '류준화',
    title: '녹색발',
    description: '',
    size: '72.7x60.6cm',
    material: '캔버스위에 아크릴, 콘테, 석회',
    year: '2015',
    edition: '',
    price: '₩5,000,000',
    images: ['260.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/396',
  },
  {
    id: '261',
    artist: '정재철',
    title: 'Middle ground',
    description: '',
    size: '73x53cm',
    material: 'oil on canvas',
    year: '2021',
    edition: '',
    price: '₩3,000,000',
    images: ['261.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/397',
  },
  {
    id: '262',
    artist: '장희진',
    title: 'folded tint',
    description: '',
    size: '61x61cm',
    material: 'acrylic, gouache, gel on modeling made canvas',
    year: '2021',
    edition: '',
    price: '₩3,000,000',
    images: ['262.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/398',
  },
  {
    id: '263',
    artist: '김주희',
    title: '월정교',
    description: `고대 이래로 미술은 정지되어 있는 상을 표현하였다. 한 순간의 시간을 표현한 인상주의에서 절정에 다다랐고, 미래파에 이르러서는 움직이는 물체를 온전하게 표현하고자 하는 시도가 행해진다. 이렇게 시간에 대한 연구는 작가들에게 중요한 과제였다. 작가는 오버랩의 효과를 이용하여 사물과 풍경의 시간을 중첩시키고 펼쳐 보인다. 하지만 여기서 작가의 욕망이 발현되는데, 단순히 시간만이 아닌 작가의 기억까지 오버랩하여 본인의 아이덴티티를 완성한다.`,
    size: '31.8x31.8cm',
    material: 'oil on canvas',
    year: '2020',
    edition: '',
    price: '₩500,000',
    images: ['263.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/399',
  },
  {
    id: '264',
    artist: '김주희',
    title: '제주 섭지코지',
    description: `고대 이래로 미술은 정지되어 있는 상을 표현하였다. 한 순간의 시간을 표현한 인상주의에서 절정에 다다랐고, 미래파에 이르러서는 움직이는 물체를 온전하게 표현하고자 하는 시도가 행해진다. 이렇게 시간에 대한 연구는 작가들에게 중요한 과제였다. 작가는 오버랩의 효과를 이용하여 사물과 풍경의 시간을 중첩시키고 펼쳐 보인다. 하지만 여기서 작가의 욕망이 발현되는데, 단순히 시간만이 아닌 작가의 기억까지 오버랩하여 본인의 아이덴티티를 완성한다.`,
    size: '53x33.3cm',
    material: 'oil on canvas',
    year: '2019',
    edition: '',
    price: '₩1,000,000',
    images: ['264.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/400',
  },
  {
    id: '265',
    artist: '김주호',
    title: '사랑만들기',
    description: '',
    size: '33x20x9cm',
    material: '조각 철판 8T',
    year: '2013',
    edition: '',
    price: '₩1,000,000',
    images: ['265.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/401',
  },
  {
    id: '266',
    artist: '김유진',
    title: '폭발의 다음',
    description: '',
    size: '26x18cm',
    material: 'paint on paper',
    year: '2021',
    edition: '',
    price: '₩200,000',
    images: ['266.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/402',
  },
  {
    id: '267',
    artist: '고자영',
    title: '이동식 정원 69-사라지는 3',
    description: '',
    size: '60x60cm',
    material: '캔버스에 유채, 아크릴채색',
    year: '2012',
    edition: '',
    price: '₩3,000,000',
    images: ['267.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/403',
  },
  {
    id: '268',
    artist: '고현주',
    title: '기억의 목소리',
    sold: true,
    description: '',
    size: '11x40inch',
    material: 'Archival Pigment print / Hahnemuhle William Turner (Edition 54/100)',
    year: '2021',
    edition: '',
    price: '₩300,000',
    images: ['268.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/404',
  },
  {
    id: '269',
    artist: '최연택',
    title: '풀',
    description: '',
    size: '37.9x45.5cm',
    material: '천위에 유채',
    year: '2025',
    edition: '',
    price: '₩1,800,000',
    images: ['269.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/405',
  },
  {
    id: '270',
    artist: '박불똥',
    title: '멸(滅)',
    sold: true,
    description: '',
    size: '40.7x58.5cm',
    material: '디지털 프린트',
    year: '1992',
    edition: '',
    price: '₩300,000',
    images: ['270.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/406',
  },
  {
    id: '271',
    artist: '이동구',
    title: '사과',
    description: '',
    size: '9x9cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩70,000',
    images: ['271.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/407',
    sold: true,
  },
  {
    id: '272',
    artist: '김남진',
    title: '누드',
    description: `김남진(金南鎭)은 1957년 충남 공주 출생으로 고려대를 졸업했다.
1987년 파인힐 갤러리에서 개인전 '이태원의 밤'과 1993년 바탕골예술관에서 '폴라로이드 누드'전을 가진 바 있다.
그가 1984년부터 시도한 일련의 '이태원의 밤' 다큐먼트는 성공한 한국사진의 자생적 형식 실험의 하나로 평가받고 있다.
이후 폴라 컬러의 이미지 전사를 이용한 누드 사진의 새로운 표현양식을 실험하였고,
1987년부터는 김남진 사진공방을 운영하며 현대사진의 제경향과 이론 그리고 사진미학을 체계화하여 국내에 소개하고 많은 후배 사진가들을 양성하였다.
전시기획자로서 서울국제사진페스티벌과 충무로사진축제를 기획•진행한 바 있으며, 현재 사진문화포럼과 갤러리 브레송의 대표로 있다.`,
    size: '확인 중',
    material: '1/5 프린트',
    year: '1992',
    edition: '에디션 1/5',
    price: '₩500,000',
    images: ['272.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/408',
  },
  {
    id: '273',
    artist: '박생광',
    title: '백두산 천지 아침',
    sold: true,
    description: '',
    size: '25.7x18.8cm',
    material: '종이, 연필',
    year: '확인 중',
    edition: '',
    price: '₩2,000,000',
    images: ['273.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/409',
  },
  {
    id: '274',
    artist: '이동구',
    title: '보리술잔',
    description: '',
    size: '12.7x10.7cm',
    material: '확인 중',
    year: '확인 중',
    edition: '',
    price: '₩30,000',
    images: ['274.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/410',
  },
  {
    id: '275',
    artist: '작가미상',
    title: '오리',
    description: '',
    size: '18x27x11cm',
    material: '도자',
    year: '확인 중',
    edition: '',
    price: '₩300,000',
    images: ['275.png'],
    shopUrl: 'https://koreasmartcoop.cafe24.com/surl/O/411',
    sold: true,
  },
];
