import { Artwork } from '@/types';

export const batch006: Artwork[] = [
  {
    id: '228',
    artist: '한미영',
    title: '연인',
    description: '',
    size: '90.9x65.1cm',
    material: 'mixed media on canvas (acrylic, gold leaf, )',
    year: '2024',
    edition: '',
    price: '₩800,000',
    image: '228.jpeg',
  },
  {
    id: '229',
    artist: '한미영',
    title: 'Free will',
    description: '',
    size: '72.7x53.0cm',
    material: 'mixed media on canvas (acrylic, gold leaf, wax paint)',
    year: '2024',
    edition: '',
    price: '₩550,000',
    image: '229.jpeg',
  },
  {
    id: '230',
    artist: '양순열',
    title: 'Ottogi Chrome Rainbow (purple top)',
    description: `작가 양순열은 회화와 조각 등 다양한 장르를 넘나드는 컨템포리 아티스트다. 작가가 평생에 걸쳐 작업을 수행해온 주제는 존재와 사물 일반에 대한 깊은 시적 공감과 연관된 것이다. 특히 그녀는 확장된 모성의 회복을 통해 이 시대가 처한 위기의 극복과, 인간/사물/자연 사이의 영적 교감의 가능성을 탐색한다.`,
    size: '60x60x130cm',
    material: 'Car paint on resin',
    year: '2022',
    edition: '',
    price: '₩35,000,000',
    image: '230.png',
  },
  {
    id: '231',
    artist: '양순열',
    title: 'Ottogi Chrome Rainbow (blue top)',
    description: `작가 양순열은 회화와 조각 등 다양한 장르를 넘나드는 컨템포리 아티스트다. 작가가 평생에 걸쳐 작업을 수행해온 주제는 존재와 사물 일반에 대한 깊은 시적 공감과 연관된 것이다. 특히 그녀는 확장된 모성의 회복을 통해 이 시대가 처한 위기의 극복과, 인간/사물/자연 사이의 영적 교감의 가능성을 탐색한다.`,
    size: '60x60x130cm',
    material: 'Car paint on resin',
    year: '2022',
    edition: '',
    price: '₩35,000,000',
    image: '231.png',
  },
  {
    id: '232',
    artist: '양순열',
    title: 'Ottogi Earthy Rainbow',
    description: `작가 양순열은 회화와 조각 등 다양한 장르를 넘나드는 컨템포리 아티스트다. 작가가 평생에 걸쳐 작업을 수행해온 주제는 존재와 사물 일반에 대한 깊은 시적 공감과 연관된 것이다. 특히 그녀는 확장된 모성의 회복을 통해 이 시대가 처한 위기의 극복과, 인간/사물/자연 사이의 영적 교감의 가능성을 탐색한다.`,
    size: '40x40x90cm',
    material: 'Car paint on resin',
    year: '2021',
    edition: '',
    price: '₩18,500,000',
    image: '232.png',
  },
  {
    id: '233',
    artist: '양순열',
    title: 'Ottogi Earthy Rainbow Matte',
    description: `작가 양순열은 회화와 조각 등 다양한 장르를 넘나드는 컨템포리 아티스트다. 작가가 평생에 걸쳐 작업을 수행해온 주제는 존재와 사물 일반에 대한 깊은 시적 공감과 연관된 것이다. 특히 그녀는 확장된 모성의 회복을 통해 이 시대가 처한 위기의 극복과, 인간/사물/자연 사이의 영적 교감의 가능성을 탐색한다.`,
    size: '40x40x65cm',
    material: 'Car paint on resin',
    year: '2021',
    edition: '',
    price: '₩12,600,000',
    image: '233.png',
  },
  {
    id: '234',
    artist: '양순열',
    title: 'Ottogi_Mother Ya-ho',
    description: `작가 양순열은 회화와 조각 등 다양한 장르를 넘나드는 컨템포리 아티스트다. 작가가 평생에 걸쳐 작업을 수행해온 주제는 존재와 사물 일반에 대한 깊은 시적 공감과 연관된 것이다. 특히 그녀는 확장된 모성의 회복을 통해 이 시대가 처한 위기의 극복과, 인간/사물/자연 사이의 영적 교감의 가능성을 탐색한다.`,
    size: '55x55x120cm',
    material: 'Car paint on resin',
    year: '2014',
    edition: '',
    price: '₩25,000,000',
    image: '234.jpeg',
  },
  {
    id: '235',
    artist: '이윤엽',
    title: '무슨일 있어?',
    description: `이윤엽은 농부나 노동자, 주변의 소박한 사물들을 재치 있게 표현하는데 흰 여백 위에 굵은 선을 사용하여 투박하면서도 정겨운 목판화의 특징을 잘 보여준다. 그에게 목판화는 나무를 깎고 작업의 도구를 다루며 그의 몸을 움직이게 만드는 매체로써, 노동을 이해하는 사람들 사이의 공감을 만들어 내거나 노동의 가치 그 자체에 대한 이해를 이끌어내는 방법이기도 하다.\n이윤엽은 공장 바닥에 까는 고무판을 사용해서 조각도로 깎아냈다. <산드래미 최씨>(1996)는 이윤엽의 첫 판화 작품으로서 당시 작가가 살던 집 근처에 살고 있던 이웃 농민을 재현한 것이다. 첫 작품 이후 작가는 본격적으로 판화를 본인의 매체로 사용하게 되는데, 특히 스스로를 ‘파견미술가’라고 부르며 파업 시위 현장 등에서 노동자들과 함께 판화를 제작하는 액티비스트로서의 작가의 면모를 드러내게 된다.`,
    size: '9.5x14cm',
    material: '확인 중',
    year: '2022',
    edition: '',
    price: '₩200,000',
    image: '235.jpeg',
  },
  {
    id: '236',
    artist: '이윤엽',
    title: '좋은소식',
    description: `이윤엽은 농부나 노동자, 주변의 소박한 사물들을 재치 있게 표현하는데 흰 여백 위에 굵은 선을 사용하여 투박하면서도 정겨운 목판화의 특징을 잘 보여준다. 그에게 목판화는 나무를 깎고 작업의 도구를 다루며 그의 몸을 움직이게 만드는 매체로써, 노동을 이해하는 사람들 사이의 공감을 만들어 내거나 노동의 가치 그 자체에 대한 이해를 이끌어내는 방법이기도 하다.\n이윤엽은 공장 바닥에 까는 고무판을 사용해서 조각도로 깎아냈다. <산드래미 최씨>(1996)는 이윤엽의 첫 판화 작품으로서 당시 작가가 살던 집 근처에 살고 있던 이웃 농민을 재현한 것이다. 첫 작품 이후 작가는 본격적으로 판화를 본인의 매체로 사용하게 되는데, 특히 스스로를 ‘파견미술가’라고 부르며 파업 시위 현장 등에서 노동자들과 함께 판화를 제작하는 액티비스트로서의 작가의 면모를 드러내게 된다.`,
    size: '27x39.5cm',
    material: '다색목판 48장 중에서',
    year: '2025',
    edition: '',
    price: '₩500,000',
    image: '236.jpeg',
  },
  {
    id: '237',
    artist: '이윤엽',
    title: '새로운 날',
    description: `이윤엽은 농부나 노동자, 주변의 소박한 사물들을 재치 있게 표현하는데 흰 여백 위에 굵은 선을 사용하여 투박하면서도 정겨운 목판화의 특징을 잘 보여준다. 그에게 목판화는 나무를 깎고 작업의 도구를 다루며 그의 몸을 움직이게 만드는 매체로써, 노동을 이해하는 사람들 사이의 공감을 만들어 내거나 노동의 가치 그 자체에 대한 이해를 이끌어내는 방법이기도 하다.\n이윤엽은 공장 바닥에 까는 고무판을 사용해서 조각도로 깎아냈다. <산드래미 최씨>(1996)는 이윤엽의 첫 판화 작품으로서 당시 작가가 살던 집 근처에 살고 있던 이웃 농민을 재현한 것이다. 첫 작품 이후 작가는 본격적으로 판화를 본인의 매체로 사용하게 되는데, 특히 스스로를 ‘파견미술가’라고 부르며 파업 시위 현장 등에서 노동자들과 함께 판화를 제작하는 액티비스트로서의 작가의 면모를 드러내게 된다.`,
    size: '26.5x80.4cm',
    material: '다색목판',
    year: '확인 중',
    edition: '',
    price: '₩1,000,000',
    image: '237.jpeg',
  },
  {
    id: '238',
    artist: '이윤엽',
    title: '콩밭메는 할머니2',
    description: `이윤엽은 농부나 노동자, 주변의 소박한 사물들을 재치 있게 표현하는데 흰 여백 위에 굵은 선을 사용하여 투박하면서도 정겨운 목판화의 특징을 잘 보여준다. 그에게 목판화는 나무를 깎고 작업의 도구를 다루며 그의 몸을 움직이게 만드는 매체로써, 노동을 이해하는 사람들 사이의 공감을 만들어 내거나 노동의 가치 그 자체에 대한 이해를 이끌어내는 방법이기도 하다.\n이윤엽은 공장 바닥에 까는 고무판을 사용해서 조각도로 깎아냈다. <산드래미 최씨>(1996)는 이윤엽의 첫 판화 작품으로서 당시 작가가 살던 집 근처에 살고 있던 이웃 농민을 재현한 것이다. 첫 작품 이후 작가는 본격적으로 판화를 본인의 매체로 사용하게 되는데, 특히 스스로를 ‘파견미술가’라고 부르며 파업 시위 현장 등에서 노동자들과 함께 판화를 제작하는 액티비스트로서의 작가의 면모를 드러내게 된다.`,
    size: '25x32.5cm',
    material: '다색목판 60장 중에서',
    year: '2009',
    edition: '',
    price: '₩400,000',
    image: '238.jpeg',
  },
  {
    id: '239',
    artist: '강석태',
    title: '나의 어린 왕자',
    description: '',
    size: '45x45cm',
    material: '캔버스에 아크릴채색',
    year: '2025',
    edition: '',
    price: '₩1,800,000',
    image: '239.jpeg',
  },
  {
    id: '240',
    artist: '강석태',
    title: '함께하는 시간',
    description: '',
    size: '40.9x31.8cm',
    material: '장지에 아크릴 채색',
    year: '2025',
    edition: '',
    price: '₩1,000,000',
    image: '240.jpeg',
  },
  {
    id: '241',
    artist: '강석태',
    title: '언제나 내 곁에',
    description: '',
    size: '72.7x60.6cm',
    material: '캔버스에 아크릴채색',
    year: '2022',
    edition: '',
    price: '₩3,600,000',
    image: '241.jpeg',
  },
  {
    id: '242',
    artist: '강석태',
    title: '어린 왕자의 별',
    description: '',
    size: '45x90cm',
    material: '캔버스에 아크릴채색',
    year: '2023',
    edition: '',
    price: '₩2,600,000',
    image: '242.jpeg',
  },
  {
    id: '243',
    artist: '강석태',
    title: '너에게로 가는 바람',
    description: '',
    size: '65x53cm',
    material: '캔버스에 아크릴채색',
    year: '2025',
    edition: '',
    price: '₩2,700,000',
    image: '243.png',
  },
  {
    id: '244',
    artist: '이문형',
    title: '책거리x크리스마스',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    image: '244.jpeg',
  },
  {
    id: '245',
    artist: '이문형',
    title: '책거리x앙리 마티스',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    image: '245.jpeg',
  },
  {
    id: '246',
    artist: '이문형',
    title: '책거리x쿠사마야요이',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    image: '246.jpeg',
  },
  {
    id: '247',
    artist: '이문형',
    title: '책거리x살바도르 달리',
    description: '',
    size: '60.6x40.9cm',
    material: '한지위에 수묵채색',
    year: '2025',
    edition: '',
    price: '₩840,000',
    image: '247.jpeg',
  },
];
