BEGIN;

-- Backfill name_en for artists matching static content (artists-data.ts)
-- Uses the same romanization as profile_en/history_en translations for consistency.

UPDATE artists SET name_en = 'Kang Seoktae' WHERE name_ko = '강석태' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Gijo' WHERE name_ko = '기조' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Gyuhak' WHERE name_ko = '김규학' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Dongseok' WHERE name_ko = '김동석' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Sanggu' WHERE name_ko = '김상구' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Youngseo' WHERE name_ko = '김영서' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Wooju' WHERE name_ko = '김우주' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Jonghwan' WHERE name_ko = '김종환' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Juho' WHERE name_ko = '김주호' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Juhee' WHERE name_ko = '김주희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Joonkwon' WHERE name_ko = '김준권' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Hoseong' WHERE name_ko = '김호성' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ra Inseok' WHERE name_ko = '라인석' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ryu Yeonbok' WHERE name_ko = '류연복' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ryu Junhwa' WHERE name_ko = '류준화' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Riho' WHERE name_ko = '리호' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'MinjeongSee' WHERE name_ko = '민정See' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Seongwan' WHERE name_ko = '박성완' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Sohyung' WHERE name_ko = '박소형' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Suji' WHERE name_ko = '박수지' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Jihye' WHERE name_ko = '박지혜' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Baek Geuma' WHERE name_ko = '백금아' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Byun Kyunghee' WHERE name_ko = '변경희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Seo Geumaeng' WHERE name_ko = '서금앵' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Son Eunyoung' WHERE name_ko = '손은영' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Son Jangsub' WHERE name_ko = '손장섭' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Song Gwangyeon' WHERE name_ko = '송광연' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Shin Gunwoo' WHERE name_ko = '신건우' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Shin Yeonjin' WHERE name_ko = '신연진' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Shin Yeri' WHERE name_ko = '신예리' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Shin Hakchul' WHERE name_ko = '신학철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'SIM_Moby' WHERE name_ko = '심모비' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Shim Hyunhee' WHERE name_ko = '심현희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Artmandu' WHERE name_ko = '아트만두' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ahn Sohyun' WHERE name_ko = '안소현' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ahn Eunkyung' WHERE name_ko = '안은경' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Yang Uncheol' WHERE name_ko = '양운철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Yemi Kim' WHERE name_ko = '예미킴' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Oa' WHERE name_ko = '오아' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Oh Yun' WHERE name_ko = '오윤' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Yun Gyeom' WHERE name_ko = '윤겸' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Gwangsu' WHERE name_ko = '이광수' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Soocheol' WHERE name_ko = '이수철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Yoll' WHERE name_ko = '이열' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Yuji' WHERE name_ko = '이유지' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Eunhwa' WHERE name_ko = '이은화' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Iktae' WHERE name_ko = '이익태' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Incheol' WHERE name_ko = '이인철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Jaejeong' WHERE name_ko = '이재정' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Jieun' WHERE name_ko = '이지은' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Cheolsu' WHERE name_ko = '이철수' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Hyunjeong' WHERE name_ko = '이현정' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Hyeseon' WHERE name_ko = '이혜선' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Hochul' WHERE name_ko = '이호철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Hongwon' WHERE name_ko = '이홍원' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jang Kyungho' WHERE name_ko = '장경호' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Geumhee' WHERE name_ko = '정금희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Mijeong' WHERE name_ko = '정미정' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Seoon' WHERE name_ko = '정서온' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Yeonsu' WHERE name_ko = '정연수' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jo Shinwook' WHERE name_ko = '조신욱' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Joo Jaehwan' WHERE name_ko = '주재환' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Choi Kyungsun' WHERE name_ko = '최경선' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Choi Yoonjung' WHERE name_ko = '최윤정' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Choi Jaeran' WHERE name_ko = '최재란' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Choi Hyesu' WHERE name_ko = '최혜수' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Han Aekyu' WHERE name_ko = '한애규' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Hong Jinhee' WHERE name_ko = '홍진희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lacey Kim' WHERE name_ko = '김레이시' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Taekyun' WHERE name_ko = '김태균' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Eunsun' WHERE name_ko = '박은선' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Hyuncheol' WHERE name_ko = '김현철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jo Irak' WHERE name_ko = '조이락' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Salnus' WHERE name_ko = 'Salnus' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Chaewon' WHERE name_ko = '이채원' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jo Munho' WHERE name_ko = '조문호' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Yeongsin' WHERE name_ko = '정영신' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Han Miyoung' WHERE name_ko = '한미영' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Yang Sunryul' WHERE name_ko = '양순열' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Yunyeop' WHERE name_ko = '이윤엽' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Munhyung' WHERE name_ko = '이문형' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Cheon Jisu' WHERE name_ko = '천지수' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ryu Hosik' WHERE name_ko = '류호식' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Jiyoung' WHERE name_ko = '김지영' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Taehee' WHERE name_ko = '김태희' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Jeongwon' WHERE name_ko = '김정원' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Min Byungsan' WHERE name_ko = '민병산' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ha Sunyoung' WHERE name_ko = '하선영' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jeong Jaecheol' WHERE name_ko = '정재철' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Jang Heejin' WHERE name_ko = '장희진' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Yujin' WHERE name_ko = '김유진' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ko Jayoung' WHERE name_ko = '고자영' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Ko Hyunju' WHERE name_ko = '고현주' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Choi Yeontaek' WHERE name_ko = '최연택' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Bulttong' WHERE name_ko = '박불똥' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Lee Donggu' WHERE name_ko = '이동구' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Kim Namjin' WHERE name_ko = '김남진' AND (name_en IS NULL OR name_en = '');
UPDATE artists SET name_en = 'Park Saenggwang' WHERE name_ko = '박생광' AND (name_en IS NULL OR name_en = '');

COMMIT;
